language: android

sudo: false

android:
  components:
  - build-tools-25.0.2
  - android-23
  - extra-android-m2repository
  - extra-android-support

jdk:
  - oraclejdk8

script:
  - "bash ./gradlew assembleRelease"
