# Disabling sudo moves build to the Container Based Infrastructure on Travis CI
sudo: false

language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-25
    - build-tools-25.0.2
    - extra-android-m2repository
    - extra-android-support

script:
  - bash ./gradlew assembleRelease  

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
